name: "Bump Version"

on:
  push:
    branches:
      - "master"

jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Automated Version Bump"
        uses: LaMobilery/gh-action-conventional-commits-npm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
